### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by kaizen1** [winkjs/wink-lemmatizer#8]
Why did you choose such a restrictive license?
This GNU stuff can't be used in the commercial world.
Would you consider updating to MIT?

**Comment by sanjayaksaxena** [comment]
Hello @kaizen1 

AGPLv3 allows you to use wink npm packages on an "**as-is**" basis in any **commercial closed-source application**. There are no restrictions on that and you are **not required to make your source code** as "**open source**" at any point. In other words, it is free for both private and commercial use.

But if you choose to enhance/modify any of the wink packages, AGPLv3 expects you to make those changes available in open source so that the community can benefit from them! 

That is our motivation behind selecting AGPLv3. 

However, we are already considering switching to MIT and will decide soon.

Best,
Sanjaya

**Comment by sanjayaksaxena** [comment]
Hello @kaizen1

We are delighted to switch `wink-lemmatizer` to the MIT license as the first package!

Best
Sanjaya

**Comment by kaizen1** [comment]
Excellent! Thanks for the update.
